apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-nginx-deployment
  labels:
    name: label-nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
     name: nginx
     labels:
       app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
  selector: 
    matchLabels:
      app: nginx 
