apiVersion: v1
kind: ReplicationController
metadata: 
  name: myreplica
  labels:
    name: myreplica
    env:  demo
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
       - name: nginx
         image: nginx

  replicas: 3
